version: '3'

volumes:
  gems:

services:
  db:
    image: danieldent/postgres-replication:9.6
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379

  server:
    build:
      dockerfile: Dockerfile
      context: ./docker
    volumes:
      - ./:/falsecoach_server
      - gems:/usr/local/bundle
    links:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_URL=postgres://postgres@db
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    command: >
      sh -c '
        bundle check || bundle install
        rm -f tmp/pids/server.pid
        bundle exec rails s -p 3000 -b 0.0.0.0
      '
